spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://dpg-cm02elud3nmc738ibae0-a.frankfurt-postgres.render.com/dbbancoejemplo1}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:hLVaFMGRQ8RjRrZfwv8KCVPv3KBUlw2g}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  graphql:
    graphiql:
      enabled: true
